name: Initialize PostgreSQL Schema

on:
  workflow_dispatch:

jobs:
  init-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL client and run SQL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          psql "$DATABASE_URL" -f scripts/init-db.sql
